services:
  - type: web
    name: blogicum
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn blogicum.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: blogicum.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '*'
